version: '3.8'

services:
  # MCP Gateway - Main entry point and load balancer
  mcp-gateway:
    image: docker/mcp-gateway:latest
    container_name: mcp-gateway
    ports:
      - "${MCP_GATEWAY_PORT:-8080}:8080"
      - "${MCP_GATEWAY_SSL_PORT:-8443}:8443"
    environment:
      - MCP_API_KEY=${MCP_API_KEY}
      - MCP_JWT_SECRET=${MCP_JWT_SECRET}
      - MCP_DOMAIN=${MCP_DOMAIN:-localhost}
      - STOUT_SERVER_URL=http://stout-server:8081
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./config:/app/config:ro
      - ./ssl:/app/ssl:ro
      - ./logs:/app/logs
    depends_on:
      - stout-server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mcp-network

  # Stout Server - High-throughput request/response processing
  stout-server:
    image: docker/mcp-stout-server:latest
    container_name: mcp-stout-server
    ports:
      - "${STOUT_SERVER_PORT:-8081}:8081"
    environment:
      - MCP_API_KEY=${MCP_API_KEY}
      - SERVER_PORT=8081
      - MAX_WORKERS=4
      - REQUEST_TIMEOUT=30
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  mcp-logs:
    driver: local
  mcp-data:
    driver: local